## Giải 100 Bài tập với Pandas

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import math

pd.options.display.max_rows = 100
pd.options.display.max_columns = 50

dtype = {
    'customer_id': str,
    'gender_cd': str,
    'postal_cd': str,
    'application_store_cd': str,
    'status_cd': str,
    'category_major_cd': str,
    'category_medium_cd': str,
    'category_small_cd': str,
    'product_cd': str,
    'store_cd': str,
    'prefecture_cd': str,
    'tel_no': str,
    'postal_cd': str,
    'street': str
}

df_customer = pd.read_csv("customer_eng.csv") 
df_geocode = pd.read_csv("geocode_eng.csv") 
df_product = pd.read_csv("product.csv") 
df_store = pd.read_csv("store_eng.csv")
df_receipt = pd.read_csv("receipt.csv")

### Phần 1: 1 - 20

---
> P-001: Từ dữ liệu biên nhận (df_receipt), hiển thị 10 bản ghi đầu tiên và kiểm tra xem loại dữ liệu nào được lưu trữ trong các cột.

In [52]:
df_receipt.head(10) # Hiện thị 10 bản ghi

,sales_ymd,sales_epoch,store_cd,receipt_no,receipt_sub_no,customer_id,product_cd,quantity,amount
0,20181103,1541203200,S14006,112,1,CS006214000001,P070305012,1,158
1,20181118,1542499200,S13008,1132,2,CS008415000097,P070701017,1,81
2,20170712,1499817600,S14028,1102,1,CS028414000014,P060101005,1,170
3,20190205,1549324800,S14042,1132,1,ZZ000000000000,P050301001,1,25
4,20180821,1534809600,S14025,1102,2,CS025415000050,P060102007,1,90
5,20190605,1559692800,S13003,1112,1,CS003515000195,P050102002,1,138
6,20181205,1543968000,S14024,1102,2,CS024514000042,P080101005,1,30
7,20190922,1569110400,S14040,1102,1,CS040415000178,P070501004,1,128
8,20170504,1493856000,S13020,1112,2,ZZ000000000000,P071302010,1,770
9,20191010,1570665600,S14027,1102,1,CS027514000015,P071101003,1,680

In [54]:
df_receipt.info() # Xem loại dữ liệu được lưu trong các cột

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104681 entries, 0 to 104680
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   sales_ymd       104681 non-null  int64
 1   sales_epoch     104681 non-null  int64
 2   store_cd        104681 non-null  object
 3   receipt_no      104681 non-null  int64
 4   receipt_sub_no  104681 non-null  int64
 5   customer_id     104681 non-null  object
 6   product_cd      104681 non-null  object
 7   quantity        104681 non-null  int64
 8   amount          104681 non-null  int64
dtypes: int64(6), object(3)
memory usage: 7.2+ MB

---
> P-002:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và hiển thị 10 bản ghi: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số tiền bán hàng (amount).

In [179]:
a = df_receipt[['sales_ymd', 'customer_id', 'product_cd','amount']] # Chỉ định các cột theo thứ tự
a.head(10) # Hiểm thị 10 dòng đầu

   sales_ymd     customer_id  product_cd  amount
0   20181103  CS006214000001  P070305012     158
1   20181118  CS008415000097  P070701017      81
2   20170712  CS028414000014  P060101005     170
3   20190205  ZZ000000000000  P050301001      25
4   20180821  CS025415000050  P060102007      90
5   20190605  CS003515000195  P050102002     138
6   20181205  CS024514000042  P080101005      30
7   20190922  CS040415000178  P070501004     128
8   20170504  ZZ000000000000  P071302010     770
9   20191010  CS027514000015  P071101003     680

---
> P-003:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và hiển thị 10 bản ghi: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số tiền bán hàng (amount). Tuy nhiên, đổi tên cột sales_ymd thành sales_date trước khi hiển thị.

In [181]:
a = df_receipt[['sales_date', 'customer_id', 'product_cd','amount']] # Đổi tên cột sales_ymd thành sales_date
a.head(10) # Xuất hiện 10 dòng đầu

   sales_date     customer_id  product_cd  amount
0    20181103  CS006214000001  P070305012     158
1    20181118  CS008415000097  P070701017      81
2    20170712  CS028414000014  P060101005     170
3    20190205  ZZ000000000000  P050301001      25
4    20180821  CS025415000050  P060102007      90
5    20190605  CS003515000195  P050102002     138
6    20181205  CS024514000042  P080101005      30
7    20190922  CS040415000178  P070501004     128
8    20170504  ZZ000000000000  P071302010     770
9    20191010  CS027514000015  P071101003     680

---
> P-004:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và trích xuất dữ liệu đáp ứng các điều kiện dưới đây: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số tiền bán hàng (amount).
> - ID khách hàng (customer_id) là "CS018205000001"

In [183]:
b = a = df_receipt[['sales_ymd', 'customer_id', 'product_cd','amount']] # Lấy cột theo điều kiện
b.loc[df_receipt.customer_id == 'CS018205000001'] # Xuất hiện cột giống với yêu càu

       sales_ymd     customer_id  product_cd  amount
36      20180911  CS018205000001  P071401012    2200
9843    20180414  CS018205000001  P060104007     600
21110   20170614  CS018205000001  P050206001     990
27673   20170614  CS018205000001  P060702015     108
27840   20190216  CS018205000001  P071005024     102
28757   20180414  CS018205000001  P071101002     278
39256   20190226  CS018205000001  P070902035     168
58121   20190924  CS018205000001  P060805001     495
68117   20190226  CS018205000001  P071401020    2200
72254   20180911  CS018205000001  P071401005    1100
88508   20190216  CS018205000001  P040101002     218
91525   20190924  CS018205000001  P091503001     280

---
> P-005:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và trích xuất dữ liệu đáp ứng tất cả các điều kiện dưới đây: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số tiền bán hàng (amount).
> - ID khách hàng (customer_id) là "CS018205000001"
> - Số tiền bán hàng (amount) lớn hơn hoặc bằng 1000

In [185]:
a = df_receipt[['sales_ymd', 'customer_id', 'product_cd','amount']] # Lấy cột theo điều kiện
a.loc[(df_receipt.customer_id == 'CS018205000001') & (df_receipt.amount >= 1000)] # Xét điều kiện

       sales_ymd     customer_id  product_cd  amount
36      20180911  CS018205000001  P071401012    2200
68117   20190226  CS018205000001  P071401020    2200
72254   20180911  CS018205000001  P071401005    1100

---
> P-006:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và trích xuất dữ liệu đáp ứng tất cả các điều kiện dưới đây: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số lượng bán hàng (quantity), số tiền bán hàng (amount).
> - ID khách hàng (customer_id) là "CS018205000001"
> - Số tiền bán hàng (amount) lớn hơn hoặc bằng 1000 hoặc số lượng bán hàng (quantity) lớn hơn hoặc bằng 5

In [187]:
c = df_receipt[['sales_ymd', 'customer_id', 'product_cd', 'quantity','amount']] # Lấy cột theo điều kiện
c.loc[(df_receipt.customer_id == 'CS018205000001') & (df_receipt.amount >= 1000) | (df_receipt.quantity >= 5)] # Xét điều kiện

       sales_ymd     customer_id  product_cd  quantity  amount
36      20180911  CS018205000001  P071401012         1    2200
9843    20180414  CS018205000001  P060104007         6     600
21110   20170614  CS018205000001  P050206001         5     990
47082   20190610  CS037414000080  P090401002         8     640
68117   20190226  CS018205000001  P071401020         1    2200
72254   20180911  CS018205000001  P071401005         1    1100

---
> P-007:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và trích xuất dữ liệu đáp ứng tất cả các điều kiện dưới đây: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số tiền bán hàng (amount).
> - ID khách hàng (customer_id) là "CS018205000001"
> - Số tiền bán hàng (amount) lớn hơn hoặc bằng 1000 và nhỏ hơn hoặc bằng 2000

In [189]:
c = df_receipt[['sales_ymd', 'customer_id', 'product_cd','amount']] # Lấy cột theo điều kiện
c.loc[(df_receipt.customer_id == 'CS018205000001') & (df_receipt.amount >= 1000) & (df_receipt.amount <= 2000)] # Xét điều kiện

       sales_ymd     customer_id  product_cd  amount
72254   20180911  CS018205000001  P071401005    1100

---
> P-008:
Từ dữ liệu biên nhận (df_receipt), chỉ định các cột theo thứ tự sau và trích xuất dữ liệu đáp ứng tất cả các điều kiện dưới đây: ngày bán hàng (sales_ymd), ID khách hàng (customer_id), mã sản phẩm (product_cd), số tiền bán hàng (amount).
> - ID khách hàng (customer_id) là "CS018205000001"
> - Mã sản phẩm (product_cd) không phải là "P071401019"

In [193]:
c = df_receipt[['sales_ymd', 'customer_id', 'product_cd','amount']] # Lấy cột theo điều kiện
c.loc[(df_receipt.customer_id == 'CS018205000001') & (df_receipt.product_cd != 'P071401019')] # Xét điều kiện

       sales_ymd     customer_id  product_cd  amount
36      20180911  CS018205000001  P071401012    2200
9843    20180414  CS018205000001  P060104007     600
21110   20170614  CS018205000001  P050206001     990
27673   20170614  CS018205000001  P060702015     108
27840   20190216  CS018205000001  P071005024     102
28757   20180414  CS018205000001  P071101002     278
39256   20190226  CS018205000001  P070902035     168
58121   20190924  CS018205000001  P060805001     495
68117   20190226  CS018205000001  P071401020    2200
72254   20180911  CS018205000001  P071401005    1100
88508   20190216  CS018205000001  P040101002     218
91525   20190924  CS018205000001  P091503001     280

---
> P-009: Thay đổi điều kiện lọc dưới đây và thay thế từ khóa OR thành AND trong truy vấn xuất dữ liệu.
> 
> `df_store.query('not(prefecture_cd == "13" | floor_area > 900)')`

In [198]:
df_store.query('not(prefecture_cd == "13" & floor_area > 900)')

,store_cd,store_name,prefecture_cd,prefecture,address,tel_no,longitude,latitude,floor_area
0,S12014,Chigakadai store,12,Chiba prefecture,"1-chome, Chigusadai, Inage-ku, Chiba-shi, Chiba",043-123-4003,140.1180,35.63559,1698.0
1,S13002,Kokubunji Temple,13,Tokyo,"Honda 2-chome, Kokubunji City, Tokyo",042-123-4008,139.4802,35.70566,1735.0
2,S14010,Kikuna store,14,Kanagawa Prefecture,"Kikuna 1-chome, Kohoku-ku, Yokohama-shi, Kanagawa",045-123-4032,139.6326,35.50049,1732.0
3,S14033,Akuwa store,14,Kanagawa Prefecture,"Akuwa Nishi 1-chome, Seya-ku, Yokohama-shi, Ka...",045-123-4043,139.4961,35.45918,1495.0
4,S14036,Sagamihara Central Store,14,Kanagawa Prefecture,"2-chome, Chuo, Sagamihara City, Kanagawa Prefe...",042-123-4045,139.3716,35.57327,1679.0
5,S13051,Itabashi Ohara store,13,Tokyo,"Ohara-cho, Itabashi-ku, Tokyo",03-0123-4029,139.6980,35.76788,1045.0
6,S13015,Southern sand store,13,Tokyo,"2-chome, Koto-ku, Tokyo 2-chome",03-0123-4014,139.8229,35.67066,1337.0
7,S14040,Nagatsuta store,14,Kanagawa Prefecture,"Nagatsuda Minamidai 5-chome, Midori-ku, Yokoha...",045-123-4046,139.4994,35.52398,1548.0
8,S13044,Minami -Rokugo store,13,Tokyo,"Minami Rokugo 2-chome, Ota-ku, Tokyo",03-0123-4028,139.7207,35.54604,1379.0
9,S14050,Akuwa Nishi store,14,Kanagawa Prefecture,"Akuwa Nishi 1-chome, Seya-ku, Yokohama-shi, Ka...",045-123-4053,139.4961,35.45918,1830.0
10,S13019,Komorone store,13,Tokyo,"Komorine 1-chome, Itabashi-ku, Tokyo",03-0123-4018,139.6795,35.74468,1004.0
11,S13052,Morino store,13,Tokyo,"Morino Sanchome, Machida City, Tokyo",042-123-4030,139.4383,35.55293,1087.0
12,S14028,Futatsu Bridge store,14,Kanagawa Prefecture,"Futatsuhashi-cho, Seya-ku, Yokohama-shi, Kanagawa",045-123-4042,139.4963,35.46304,1574.0
13,S13031,Hatsudai store,13,Tokyo,"Hatsudai 2-chome, Shibuya-ku, Tokyo",03-0123-4020,139.6862,35.67616,986.0
14,S13038,Higashikasai store,13,Tokyo,"Tokyo Kasai 9-chome, Edogawa-ku, Tokyo",03-0123-4024,139.8826,35.65366,1184.0
15,S13001,Naka -Rokugo store,13,Tokyo,"2-chome, Nakarokugo, Ota-ku, Tokyo",03-1234-4007,139.7132,35.55135,1796.0
16,S14012,Honmaki Wada store,14,Kanagawa Prefecture,"Honmaki Wada, Naka-ku, Yokohama-shi, Kanagawa",045-123-4034,139.6582,35.42156,1341.0
17,S13004,Sagimiya store,13,Tokyo,"Saginomiya Sanchome, Nakano-ku, Tokyo",03-0123-4010,139.6421,35.72348,947.0
18,S14046,Kitayamada store,14,Kanagawa Prefecture,"Kitamada 1-chome, Tsuzuki-ku, Yokohama-shi, Ka...",045-123-4049,139.5916,35.56189,831.0
19,S14022,Zushi store,14,Kanagawa Prefecture,"Zushi 1-chome, Zushi City, Kanagawa Prefecture",046-123-4036,139.5789,35.29642,1838.0
20,S14011,Hiyoshi Honmachi store,14,Kanagawa Prefecture,"4-chome Honcho, Kohoku-ku, Yokohama-shi, Kanagawa",045-123-4033,139.6316,35.54655,890.0
21,S13016,Koganei store,13,Tokyo,"1-chome Honmachi, Koganei-shi, Tokyo",042-123-4015,139.5094,35.70018,1399.0
22,S14034,Kawasaki Nogawa store,14,Kanagawa Prefecture,"Nogawa, Miyamae-ku, Kawasaki City, Kanagawa Pr...",044-123-4044,139.5998,35.57693,1318.0
23,S13008,Seijo store,13,Tokyo,"Seijo 3-chome, Setagaya-ku, Tokyo",03-0123-4012,139.5966,35.63614,883.0
24,S13020,Jujo Nakahara store,13,Tokyo,"Jujo Nakahara Sanchome, Kita-ku, Tokyo",03-0123-4019,139.7186,35.76686,801.0
25,S13043,Minami -Shinagawa store,13,Tokyo,"Minami-Shinagawa Sanchome, Shinagawa-ku, Tokyo",03-0123-4027,139.7436,35.60981,845.0
26,S14048,Nakagawa Chuo store,14,Kanagawa Prefecture,"2-chome Nakagawa Chuo 2-chome, Tsuzuki-ku, Yok...",045-123-4051,139.5758,35.54912,1657.0
27,S12007,Sakura store,12,Chiba prefecture,"Kamishizu, Sakura City, Chiba Prefecture",043-123-4001,140.1452,35.71872,1895.0
28,S14026,Tsujido west coast store,14,Kanagawa Prefecture,"2-chome, Tsujido, Fujisawa City, Kanagawa Pref...",046-123-4040,139.4466,35.32464,1732.0
29,S13041,Hachioji store,13,Tokyo,"Otsuka, Hachioji, Tokyo",042-123-4026,139.4235,35.63787,810.0
30,S13017,Koenji Minami store,13,Tokyo,"Koenji Minami 4-chome, Suginami-ku, Tokyo",03-0123-4016,139.6513,35.70273,841.0
31,S14049,Kawasaki Daishi store,14,Kanagawa Prefecture,"Nakase Sanchome, Kawasaki-ku, Kawasaki City, K...",044-123-4052,139.7327,35.53759,962.0
32,S14023,Kawasaki store,14,Kanagawa Prefecture,"2-chome Honmachi, Kawasaki-ku, Kawasaki-shi, K...",044-123-4037,139.7028,35.53599,1804.0
33,S13018,Kiyose store,13,Tokyo,"Matsuyama 1-chome, Kiyose City, Tokyo",042-123-4017,139.5178,35.76885,1220.0
34,S13035,Yoga 4 -chome store,13,Tokyo,"Yoga 4-chome, Setagaya-ku, Tokyo",03-0123-4022,139.6318,35.63029,988.0
35,S14027,Minami -Fujizawa store,14,Kanagawa Prefecture,"Minami Fujisawa, Fujisawa City, Kanagawa Prefe...",046-123-4041,139.4896,35.33762,1521.0
36,S14021,Isehara store,14,Kanagawa Prefecture,"Isehara 4-chome, Isehara City, Kanagawa Prefec...",046-123-4035,139.3129,35.40169,962.0
37,S14047,Sagamihara store,14,Kanagawa Prefecture,"6-chome, Chiyoda, Sagamihara City, Kanagawa Pr...",042-123-4050,139.3748,35.55959,1047.0
38,S12013,Narashino store,12,Chiba prefecture,"1-chome Shibaen, Narashino City, Chiba Prefecture",047-123-4002,140.0220,35.66122,808.0
39,S13032,Naka -Rokugo store,13,Tokyo,"Nakarokugo Sanchome, Ota-ku, Tokyo",03-0123-4021,139.7123,35.54682,1354.0
40,S14042,Niiyama Shinto store,14,Kanagawa Prefecture,"Shinyamashita 2-chome, Naka-ku, Yokohama-shi, ...",045-123-4047,139.6593,35.43894,1044.0
41,S13039,Minamiogikubo store,13,Tokyo,"Minamiogikubo 4-chome, Suginami-ku, Tokyo",03-0123-4025,139.6152,35.70045,1133.0
42,S12030,Yawata store,12,Chiba prefecture,"Yawata 3-chome, Ichikawa City, Chiba Prefecture",047-123-4005,139.9240,35.72318,1162.0
43,S13009,Yoga store,13,Tokyo,"Setagaya-ku, Tokyo Kaga 2-chome",03-0123-4013,139.6382,35.62720,1243.0
44,S14025,Yamato store,14,Kanagawa Prefecture,"Shimwada, Yamato City, Kanagawa Prefecture",046-123-4039,139.4680,35.43414,1011.0
45,S14045,Atsugi store,14,Kanagawa Prefecture,"2-chome Nakamachi, Atsugi City, Kanagawa Prefe...",046-123-4048,139.3651,35.44182,980.0
46,S13005,Shirasagi store,13,Tokyo,"Shirasagi Sanchome, Nakano-ku, Tokyo",03-0123-4011,139.6307,35.72246,1259.0
47,S12029,Higashino store,12,Chiba prefecture,"1-chome Higashino, Urayasu City, Chiba Prefecture",047-123-4004,139.8968,35.65086,1101.0
48,S13003,Komae store,13,Tokyo,"Komae City, Tokyo Izumi Honcho 4-chome",03-0123-4009,139.5668,35.64462,1529.0
49,S12053,Takasu store,12,Chiba prefecture,"Takasu 5-chome, Urayasu City, Chiba Prefecture",047-123-4006,139.9176,35.63755,1555.0
50,S13037,Minamisuna 1 -chome store,13,Tokyo,"Koto-ku, Tokyo Minamisuna 1-chome",03-0123-4023,139.8215,35.67898,814.0
51,S14024,Mita store,14,Kanagawa Prefecture,"Mita 4-chome, Tama-ku, Kawasaki City, Kanagawa...",044-123-4038,139.5424,35.60770,972.0
52,S14006,Kuzugaya store,14,Kanagawa Prefecture,"Kuzugaya, Tsuzuki-ku, Yokohama City, Kanagawa ...",045-123-4031,139.5633,35.53573,1886.0

---
> P-010:
Từ dữ liệu cửa hàng (df_store), trích xuất và hiển thị 10 bản ghi với mã cửa hàng (store_cd) bắt đầu bằng 'S14'.

In [205]:
d = df_store.query('not(store_cd == "S14")')
d.head(10)

,store_cd,store_name,prefecture_cd,prefecture,address,tel_no,longitude,latitude,floor_area
0,S12014,Chigakadai store,12,Chiba prefecture,"1-chome, Chigusadai, Inage-ku, Chiba-shi, Chiba",043-123-4003,140.1180,35.63559,1698.0
1,S13002,Kokubunji Temple,13,Tokyo,"Honda 2-chome, Kokubunji City, Tokyo",042-123-4008,139.4802,35.70566,1735.0
2,S14010,Kikuna store,14,Kanagawa Prefecture,"Kikuna 1-chome, Kohoku-ku, Yokohama-shi, Kanagawa",045-123-4032,139.6326,35.50049,1732.0
3,S14033,Akuwa store,14,Kanagawa Prefecture,"Akuwa Nishi 1-chome, Seya-ku, Yokohama-shi, Ka...",045-123-4043,139.4961,35.45918,1495.0
4,S14036,Sagamihara Central Store,14,Kanagawa Prefecture,"2-chome, Chuo, Sagamihara City, Kanagawa Prefe...",042-123-4045,139.3716,35.57327,1679.0
5,S13051,Itabashi Ohara store,13,Tokyo,"Ohara-cho, Itabashi-ku, Tokyo",03-0123-4029,139.6980,35.76788,1045.0
6,S13015,Southern sand store,13,Tokyo,"2-chome, Koto-ku, Tokyo 2-chome",03-0123-4014,139.8229,35.67066,1337.0
7,S14040,Nagatsuta store,14,Kanagawa Prefecture,"Nagatsuda Minamidai 5-chome, Midori-ku, Yokoha...",045-123-4046,139.4994,35.52398,1548.0
8,S13044,Minami -Rokugo store,13,Tokyo,"Minami Rokugo 2-chome, Ota-ku, Tokyo",03-0123-4028,139.7207,35.54604,1379.0
9,S14050,Akuwa Nishi store,14,Kanagawa Prefecture,"Akuwa Nishi 1-chome, Seya-ku, Yokohama-shi, Ka...",045-123-4053,139.4961,35.45918,1830.0